
export const WORD_CATEGORIES = {
  ANIMALS: [
    'LION', 'TIGER', 'ELEPHANT', 'GIRAFFE', 'ZEBRA',
    'MONKEY', 'KANGAROO', 'PANDA', 'KOALA', 'PENGUIN',
    'DOLPHIN', 'WHALE', 'SHARK', 'EAGLE', 'HAWK',
    'PARROT', 'FLAMINGO', 'CHEETAH', 'LEOPARD', 'WOLF',
    'BEAR', 'RABBIT', 'TURTLE', 'SNAKE', 'CROCODILE',
    'OTTER', 'SEAL', 'OCTOPUS', 'CRAB', 'LOBSTER',
    'OWL', 'SWAN', 'DUCK', 'GOOSE', 'TURKEY',
    'DEER', 'MOOSE', 'FOX', 'RACCOON', 'SQUIRREL'
  ],
  TECHNOLOGY: [
    'COMPUTER', 'INTERNET', 'SOFTWARE', 'HARDWARE', 'KEYBOARD',
    'MONITOR', 'LAPTOP', 'TABLET', 'SMARTPHONE', 'DATABASE',
    'NETWORK', 'SERVER', 'BROWSER', 'WEBSITE', 'PROGRAM',
    'CODING', 'ALGORITHM', 'PIXEL', 'DIGITAL', 'WIRELESS',
    'ROBOT', 'CYBORG', 'VIRTUAL', 'REALITY', 'AUGMENTED',
    'CLOUD', 'STORAGE', 'MEMORY', 'PROCESSOR', 'CIRCUIT',
    'BATTERY', 'SCREEN', 'MOUSE', 'PRINTER', 'SCANNER',
    'ROUTER', 'MODEM', 'CABLE', 'SATELLITE', 'SIGNAL'
  ],
  FOOD: [
    'PIZZA', 'BURGER', 'PASTA', 'SALAD', 'SANDWICH',
    'STEAK', 'CHICKEN', 'SUSHI', 'TACO', 'BURRITO',
    'APPLE', 'BANANA', 'ORANGE', 'GRAPE', 'STRAWBERRY',
    'CHOCOLATE', 'ICECREAM', 'COOKIE', 'DONUT', 'CAKE',
    'BREAD', 'CHEESE', 'BUTTER', 'YOGURT', 'MILK',
    'COFFEE', 'TEA', 'JUICE', 'WATER', 'SODA',
    'RICE', 'NOODLE', 'SOUP', 'STEW', 'CURRY',
    'POTATO', 'TOMATO', 'ONION', 'CARROT', 'SPINACH'
  ],
  COUNTRIES: [
    'USA', 'CANADA', 'MEXICO', 'BRAZIL', 'ARGENTINA',
    'UK', 'FRANCE', 'GERMANY', 'ITALY', 'SPAIN',
    'RUSSIA', 'CHINA', 'JAPAN', 'INDIA', 'AUSTRALIA',
    'EGYPT', 'KENYA', 'SOUTHAFRICA', 'NEWZEALAND', 'IRELAND',
    'SWEDEN', 'NORWAY', 'FINLAND', 'DENMARK', 'ICELAND',
    'POLAND', 'GREECE', 'TURKEY', 'THAILAND', 'VIETNAM',
    'KOREA', 'INDONESIA', 'MALAYSIA', 'SINGAPORE', 'PHILIPPINES',
    'CHILE', 'PERU', 'COLOMBIA', 'VENEZUELA', 'CUBA'
  ],
  SPORTS: [
    'SOCCER', 'BASKETBALL', 'BASEBALL', 'FOOTBALL', 'TENNIS',
    'GOLF', 'CRICKET', 'RUGBY', 'HOCKEY', 'VOLLEYBALL',
    'SWIMMING', 'RUNNING', 'CYCLING', 'BOXING', 'SKIING',
    'SURFING', 'SKATING', 'KARATE', 'YOGA', 'DANCING',
    'WRESTLING', 'JUDO', 'FENCING', 'ARCHERY', 'SHOOTING',
    'ROWING', 'SAILING', 'DIVING', 'GYMNASTICS', 'ATHLETICS',
    'BADMINTON', 'SQUASH', 'HANDBALL', 'POLO', 'LACROSSE',
    'CURLING', 'BOWLING', 'BILLIARDS', 'DARTS', 'CHESS'
  ],
  NATURE: [
    'TREE', 'FLOWER', 'GRASS', 'FOREST', 'JUNGLE',
    'MOUNTAIN', 'RIVER', 'OCEAN', 'LAKE', 'DESERT',
    'RAIN', 'SNOW', 'WIND', 'STORM', 'THUNDER',
    'SUN', 'MOON', 'STAR', 'PLANET', 'GALAXY',
    'CLOUD', 'SKY', 'EARTH', 'FIRE', 'WATER',
    'STONE', 'ROCK', 'SAND', 'SOIL', 'MUD',
    'LEAF', 'ROOT', 'BRANCH', 'SEED', 'FRUIT',
    'SUMMER', 'WINTER', 'SPRING', 'AUTUMN', 'SEASON'
  ],
  HOUSE: [
    'KITCHEN', 'BEDROOM', 'BATHROOM', 'LIVING', 'DINING',
    'GARAGE', 'GARDEN', 'ROOF', 'FLOOR', 'WALL',
    'WINDOW', 'DOOR', 'STAIRS', 'HALL', 'ATTIC',
    'TABLE', 'CHAIR', 'SOFA', 'BED', 'DESK',
    'LAMP', 'RUG', 'MIRROR', 'CLOCK', 'SHELF',
    'FRIDGE', 'OVEN', 'STOVE', 'SINK', 'TOILET',
    'SHOWER', 'TUB', 'TOWEL', 'SOAP', 'BRUSH'
  ],
  JOBS: [
    'DOCTOR', 'NURSE', 'TEACHER', 'POLICE', 'FIREFIGHTER',
    'CHEF', 'WAITER', 'ARTIST', 'SINGER', 'ACTOR',
    'PILOT', 'DRIVER', 'FARMER', 'LAWYER', 'JUDGE',
    'ENGINEER', 'SCIENTIST', 'WRITER', 'EDITOR', 'DESIGNER',
    'DENTIST', 'SURGEON', 'VET', 'BAKER', 'BUTCHER',
    'PLUMBER', 'ELECTRICIAN', 'MECHANIC', 'CARPENTER', 'PAINTER',
    'SOLDIER', 'SAILOR', 'ASTRONAUT', 'DETECTIVE', 'GUARD',
    'COACH', 'ATHLETE', 'JUDGE', 'MAYOR', 'PRESIDENT'
  ],
  CLOTHING: [
    'SHIRT', 'PANTS', 'DRESS', 'SKIRT', 'JACKET',
    'COAT', 'SWEATER', 'HOODIE', 'VEST', 'SUIT',
    'TIE', 'SCARF', 'GLOVES', 'HAT', 'CAP',
    'SOCKS', 'SHOES', 'BOOTS', 'SANDALS', 'HEELS',
    'BELT', 'WATCH', 'GLASSES', 'RING', 'CHAIN',
    'JEANS', 'SHORTS', 'SWIMSUIT', 'PAJAMAS', 'ROBE',
    'BUTTON', 'ZIPPER', 'POCKET', 'COLLAR', 'SLEEVE',
    'COTTON', 'WOOL', 'SILK', 'LEATHER', 'DENIM'
  ],
  BODY: [
    'HEAD', 'HAIR', 'FACE', 'EYE', 'NOSE',
    'EAR', 'MOUTH', 'TOOTH', 'TONGUE', 'LIP',
    'NECK', 'SHOULDER', 'ARM', 'ELBOW', 'HAND',
    'FINGER', 'CHEST', 'STOMACH', 'BACK', 'LEG',
    'KNEE', 'FOOT', 'TOE', 'SKIN', 'BONE',
    'HEART', 'BRAIN', 'LUNG', 'BLOOD', 'MUSCLE',
    'THUMB', 'WRIST', 'ANKLE', 'HEEL', 'CHIN',
    'CHEEK', 'FOREHEAD', 'EYEBROW', 'EYELASH', 'NAIL'
  ],
  SPACE: [
    'PLANET', 'GALAXY', 'ASTEROID', 'COMET', 'METEOR',
    'ORBIT', 'GRAVITY', 'ROCKET', 'SHUTTLE', 'STATION',
    'ALIEN', 'UFO', 'COSMOS', 'NEBULA', 'SUPERNOVA',
    'QUASAR', 'BLACKHOLE', 'TELESCOPE', 'CRATER', 'ZODIAC',
    'MARS', 'VENUS', 'SATURN', 'JUPITER', 'NEPTUNE',
    'URANUS', 'PLUTO', 'MERCURY', 'EARTH', 'SUN'
  ],
  COLORS: [
    'RED', 'BLUE', 'GREEN', 'YELLOW', 'ORANGE',
    'PURPLE', 'PINK', 'BROWN', 'BLACK', 'WHITE',
    'GRAY', 'GOLD', 'SILVER', 'BRONZE', 'VIOLET',
    'INDIGO', 'MAGENTA', 'TEAL', 'CYAN', 'BEIGE',
    'MAROON', 'NAVY', 'OLIVE', 'CORAL', 'PEACH',
    'LAVENDER', 'TURQUOISE', 'AZURE', 'CRIMSON', 'LIME'
  ],
  INSTRUMENTS: [
    'PIANO', 'GUITAR', 'DRUMS', 'VIOLIN', 'FLUTE',
    'TRUMPET', 'SAXOPHONE', 'CLARINET', 'CELLO', 'HARP',
    'BANJO', 'TUBA', 'TROMBONE', 'OBOE', 'ACCORDION',
    'KEYBOARD', 'SYNTH', 'BASS', 'UKULELE', 'MANDOLIN',
    'SITAR', 'LUTE', 'XYLOPHONE', 'GONG', 'CHIME',
    'ORGAN', 'HARMONICA', 'BAGPIPES', 'FIDDLE', 'KAZOO'
  ],
  WEATHER: [
    'SUNNY', 'CLOUDY', 'RAINY', 'STORMY', 'WINDY',
    'SNOWY', 'FOGGY', 'MISTY', 'HAZY', 'ICY',
    'HOT', 'COLD', 'WARM', 'COOL', 'DRY',
    'WET', 'HUMID', 'MILD', 'FREEZING', 'BOILING',
    'THUNDER', 'LIGHTNING', 'TORNADO', 'HURRICANE', 'CYCLONE',
    'TYPHOON', 'BLIZZARD', 'DROUGHT', 'FLOOD', 'MONSOON'
  ],
  TRANSPORT: [
    'CAR', 'BUS', 'TRUCK', 'VAN', 'BIKE',
    'TRAIN', 'PLANE', 'BOAT', 'SHIP', 'FERRY',
    'TAXI', 'SUBWAY', 'METRO', 'TRAM', 'SCOOTER',
    'MOPED', 'HELICOPTER', 'JET', 'GLIDER', 'BALLOON',
    'ROCKET', 'SKATEBOARD', 'ROLLERBLADE', 'UNICYCLE', 'RICKSHAW',
    'SEGWAY', 'HOVERBOARD', 'TRACTOR', 'AMBULANCE', 'CRANE'
  ],
  FRUITS: [
    'APPLE', 'BANANA', 'ORANGE', 'GRAPE', 'STRAWBERRY',
    'BLUEBERRY', 'RASPBERRY', 'BLACKBERRY', 'MANGO', 'PINEAPPLE',
    'PEACH', 'PEAR', 'PLUM', 'CHERRY', 'APRICOT',
    'LEMON', 'LIME', 'GRAPEFRUIT', 'MELON', 'WATERMELON',
    'KIWI', 'PAPAYA', 'GUAVA', 'FIG', 'DATE',
    'COCONUT', 'AVOCADO', 'POMEGRANATE', 'LYCHEE', 'DRAGONFRUIT',
    'PASSIONFRUIT', 'PERSIMMON', 'DURIAN', 'STARFRUIT', 'KUMQUAT'
  ],
  VEGETABLES: [
    'CARROT', 'POTATO', 'ONION', 'GARLIC', 'GINGER',
    'BROCCOLI', 'CAULIFLOWER', 'CABBAGE', 'SPINACH', 'KALE',
    'LETTUCE', 'CELERY', 'CUCUMBER', 'ASPARAGUS', 'PEPPER',
    'TOMATO', 'EGGPLANT', 'ZUCCHINI', 'SQUASH', 'PUMPKIN',
    'CORN', 'PEAS', 'BEANS', 'RADISH', 'BEET',
    'TURNIP', 'PARSNIP', 'YAM', 'SWEETPOTATO', 'MUSHROOM',
    'ARTICHOKE', 'OKRA', 'FENNEL', 'LEEK', 'SCALLION'
  ],
  EMOTIONS: [
    'HAPPY', 'SAD', 'ANGRY', 'EXCITED', 'SCARED',
    'NERVOUS', 'BORED', 'TIRED', 'RELAXED', 'CALM',
    'CONFUSED', 'SURPRISED', 'SHOCKED', 'PROUD', 'ASHAMED',
    'GUILTY', 'JEALOUS', 'ENVIOUS', 'LOVED', 'HATED',
    'LONELY', 'HOPEFUL', 'HOPELESS', 'GRATEFUL', 'THANKFUL',
    'CONTENT', 'SATISFIED', 'JOYFUL', 'CHEERFUL', 'GLAD',
    'MISERABLE', 'DEPRESSED', 'ANXIOUS', 'WORRIED', 'STRESSED'
  ],
  SCHOOL: [
    'SCHOOL', 'CLASS', 'TEACHER', 'STUDENT', 'DESK',
    'CHAIR', 'BOARD', 'CHALK', 'MARKER', 'ERASER',
    'PENCIL', 'PEN', 'PAPER', 'NOTEBOOK', 'BOOK',
    'HOMEWORK', 'EXAM', 'TEST', 'QUIZ', 'GRADE',
    'SUBJECT', 'MATH', 'SCIENCE', 'HISTORY', 'ENGLISH',
    'ART', 'MUSIC', 'GYM', 'RECESS', 'LUNCH',
    'LIBRARY', 'PRINCIPAL', 'NURSE', 'JANITOR', 'BUS'
  ]
};

export const ALL_WORDS = [
  ...WORD_CATEGORIES.ANIMALS,
  ...WORD_CATEGORIES.TECHNOLOGY,
  ...WORD_CATEGORIES.FOOD,
  ...WORD_CATEGORIES.COUNTRIES,
  ...WORD_CATEGORIES.SPORTS,
  ...WORD_CATEGORIES.NATURE,
  ...WORD_CATEGORIES.HOUSE,
  ...WORD_CATEGORIES.JOBS,
  ...WORD_CATEGORIES.CLOTHING,
  ...WORD_CATEGORIES.BODY,
  ...WORD_CATEGORIES.SPACE,
  ...WORD_CATEGORIES.COLORS,
  ...WORD_CATEGORIES.INSTRUMENTS,
  ...WORD_CATEGORIES.WEATHER,
  ...WORD_CATEGORIES.TRANSPORT,
  ...WORD_CATEGORIES.FRUITS,
  ...WORD_CATEGORIES.VEGETABLES,
  ...WORD_CATEGORIES.EMOTIONS,
  ...WORD_CATEGORIES.SCHOOL
];

export function getRandomWords(count: number = 10): string[] {
  // Shuffle array
  const shuffled = [...ALL_WORDS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
